services:
  web:
    image: kubedevio/rotten-potatoes:v1
    ports:
      - "8080:5000"
    networks:
      - prometheus
    depends_on:
      - mongodb
    environment:
      MONGODB_DB: "admin"
      MONGODB_HOST: "mongodb"
      MONGODB_PORT: "27017"
      MONGODB_USERNAME: "mongouser"
      MONGODB_PASSWORD: "mongopwd"

  mongodb:
    image: mongo:7.0
    volumes:
      - db_mongo:/data/db
    networks:
      - prometheus
volumes:
  db_mongo:
networks:
  prometheus: 
    driver: bridge